routes:
  /api/version:
    GET:
      - statusCode: 200
        delay: 1000
        filename: stub_version.json
  /api/rooms:
    GET:
      - statusCode: 200
        delay: 500
        filename: stub_chatrooms_list.json
    PUT:
      - statusCode: 200
        delay: 500
        filename: stub_chatrooms_list.json
    POST:
      - statusCode: 200
        delay: 500
        filename: stub_chatroom_details.json
    DELETE:
      - statusCode: 200
        delay: 500
        filename: stub_success.json
  /api/rooms/join:
    POST:
      - statusCode: 200
        delay: 500
        filename: stub_chatroom_details.json
  /api/users:
    POST:
      - statusCode: 200
        delay: 500
        filename: stub_update_user.json
    PUT:
      - statusCode: 200
        delay: 500
        filename: stub_update_user.json
  /api/messages:
    GET:
      - statusCode: 200
        delay: 500
        filename: stub_messages.json
