routes:
  /api/version:
    GET:
      - statusCode: 200
        delay: 1000
        filename: stub_version.json
  /api/rooms:
    GET:
      - statusCode: 200
        delay: 500
        filename: stub_chatrooms_list.json
  /api/rooms/join:
    POST:
      - statusCode: 200
        delay: 500
        filename: stub_chatroom_details.json