routes:
  /api/version:
    GET:
      - statusCode: 200
        delay: 1000
        filename: stub_version.json
  /rooms:
    GET:
      - statusCode: 200
        delay: 500
        filename: stub_chatrooms_list.json
